configs:
  client:
    default:
      address: web-888.local
      recorder_path: ../red-pitaya-notes/projects/hfdl_receiver/client/redpitayarecorder.py
      channel_width: 307200
  decoder:
    default:
#      sample-rates: [256000]
      station_id: RP-KLDJ-HFDL
      output:
        - format: json
          protocol: tcp
          address: rphs-planes.lan
          port: 5556
observer:
  all_receivers:
    redpitaya-00:
      config: web888
      client:
        port: 9000
    redpitaya-01:
      config: web888
      client:
        port: 9001
    redpitaya-02:
      config: web888
      client:
        port: 9002
    redpitaya-03:
      config: web888
      client:
        port: 9003
    redpitaya-04:
      config: web888
      client:
        port: 9004
    redpitaya-05:
      config: web888
      client:
        port: 9005
    redpitaya-06:
      config: web888
      client:
        port: 9006
    redpitaya-07:
      config: web888
      client:
        port: 9007
    redpitaya-08:
      config: web888
      client:
        port: 9008
    redpitaya-09:
      config: web888
      client:
        port: 9009
    redpitaya-10:
      config: web888
      client:
        port: 9010
    redpitaya-11:
      config: web888
      client:
        port: 9011
    redpitaya-12:
      config: web888
      client:
        port: 9012
  local_receivers:
    - redpitaya-00
    - redpitaya-01
    - redpitaya-02
    - redpitaya-03
    - redpitaya-04
    - redpitaya-05
    - redpitaya-06
    - redpitaya-07
    - redpitaya-08
    - redpitaya-09
    - redpitaya-10
    - redpitaya-11
    - redpitaya-12
  conductor:
    ranked_stations:
    - 4
    - 11
    - 1
    - 3
    - 7
    - 17
    - 9
    - 13
    - 2
    - 14
    - 15
    - 10
    - 16
    - 8
    - 5
    - 6
  tracker:
    station_updates:
    - period: 61
      url: https://hfdl.observer/active.json
cui:
  ticker:
    bin_size: 360
    show_quiet: false
